/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BlacksmithTest.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, Html, useAnimations} from "@react-three/drei";
import { folder, button, useControls } from "leva";
import * as THREE from "three";
import useVisemeAnimationCC4 from "../hooks/useVisemeAnimationCC4";
import useCharacterAnimationCC4 from "../hooks/useCharacterAnimationCC4";

export function Smith(props) {
  const {nodes, materials, scene } = useGLTF('models/BlacksmithTest.glb')
  const group = useRef();


  useEffect(() => {
    scene.traverse((obj) => {
      if (obj.isSkinnedMesh) {
        const hasGeometry = obj.geometry && obj.geometry.attributes?.position;

        if (!hasGeometry) {
          console.warn('Disabling broken SkinnedMesh:', obj.name);
          obj.visible = false; // Hide broken mesh
        }
      }
    });
  }, [scene]);
  


  return (
    <group {...props} dispose={null} ref={group}>
      <group scale={0.01}>
        <primitive object={nodes.CC_Base_BoneRoot} />
        <skinnedMesh geometry={nodes.Butcher_s_Apron_Bonus.geometry} material={materials['Apron_Full.001']} skeleton={nodes.Butcher_s_Apron_Bonus.skeleton} />
        <skinnedMesh geometry={nodes.Butcher_s_Boots_Bonus.geometry} material={materials['Boots.001']} skeleton={nodes.Butcher_s_Boots_Bonus.skeleton} />
        <skinnedMesh geometry={nodes.Butcher_s_Shirt_Bonus.geometry} material={materials['Shirt.001']} skeleton={nodes.Butcher_s_Shirt_Bonus.skeleton} />
        <skinnedMesh geometry={nodes.Butcher_s_Trousers_Bonus.geometry} material={materials['Trousers.001']} skeleton={nodes.Butcher_s_Trousers_Bonus.skeleton} />
        <skinnedMesh geometry={nodes.Hook.geometry} material={materials['Hook.001']} skeleton={nodes.Hook.skeleton} />
        <skinnedMesh geometry={nodes.Rags.geometry} material={materials['Rags.001']} skeleton={nodes.Rags.skeleton} />
        <skinnedMesh name="Butcher_s_Mustache" geometry={nodes.Butcher_s_Mustache.geometry} material={materials['Beard_Transparency.003']} skeleton={nodes.Butcher_s_Mustache.skeleton} morphTargetDictionary={nodes.Butcher_s_Mustache.morphTargetDictionary} morphTargetInfluences={nodes.Butcher_s_Mustache.morphTargetInfluences} />
        <skinnedMesh name="Butcher_s_Sideburns" geometry={nodes.Butcher_s_Sideburns.geometry} material={materials['Beard_Transparency.002']} skeleton={nodes.Butcher_s_Sideburns.skeleton} morphTargetDictionary={nodes.Butcher_s_Sideburns.morphTargetDictionary} morphTargetInfluences={nodes.Butcher_s_Sideburns.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Tongue" geometry={nodes.CC_Base_Tongue.geometry} material={materials['Std_Tongue.001']} skeleton={nodes.CC_Base_Tongue.skeleton} morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences} />
        <skinnedMesh name="Butcher_s_Brows001" geometry={nodes.Butcher_s_Brows001.geometry} material={materials['Male_Bushy_Transparency.001']} skeleton={nodes.Butcher_s_Brows001.skeleton} morphTargetDictionary={nodes.Butcher_s_Brows001.morphTargetDictionary} morphTargetInfluences={nodes.Butcher_s_Brows001.morphTargetInfluences} />
        <skinnedMesh name="Butcher_s_Brows001_1" geometry={nodes.Butcher_s_Brows001_1.geometry} material={materials['Male_Bushy_Base_Transparency.001']} skeleton={nodes.Butcher_s_Brows001_1.skeleton} morphTargetDictionary={nodes.Butcher_s_Brows001_1.morphTargetDictionary} morphTargetInfluences={nodes.Butcher_s_Brows001_1.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001" geometry={nodes.CC_Base_Body001.geometry} material={materials['Std_Skin_Head.001']} skeleton={nodes.CC_Base_Body001.skeleton} morphTargetDictionary={nodes.CC_Base_Body001.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001_1" geometry={nodes.CC_Base_Body001_1.geometry} material={materials['Std_Skin_Body.001']} skeleton={nodes.CC_Base_Body001_1.skeleton} morphTargetDictionary={nodes.CC_Base_Body001_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001_1.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001_2" geometry={nodes.CC_Base_Body001_2.geometry} material={materials['Std_Skin_Arm.001']} skeleton={nodes.CC_Base_Body001_2.skeleton} morphTargetDictionary={nodes.CC_Base_Body001_2.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001_2.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001_3" geometry={nodes.CC_Base_Body001_3.geometry} material={materials['Std_Skin_Leg.001']} skeleton={nodes.CC_Base_Body001_3.skeleton} morphTargetDictionary={nodes.CC_Base_Body001_3.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001_3.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001_4" geometry={nodes.CC_Base_Body001_4.geometry} material={materials['Std_Nails.001']} skeleton={nodes.CC_Base_Body001_4.skeleton} morphTargetDictionary={nodes.CC_Base_Body001_4.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001_4.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Body001_5" geometry={nodes.CC_Base_Body001_5.geometry} material={materials['Std_Eyelash.001']} skeleton={nodes.CC_Base_Body001_5.skeleton} morphTargetDictionary={nodes.CC_Base_Body001_5.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body001_5.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Eye001" geometry={nodes.CC_Base_Eye001.geometry} material={materials['Std_Eye_R.001']} skeleton={nodes.CC_Base_Eye001.skeleton} morphTargetDictionary={nodes.CC_Base_Eye001.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Eye001.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Eye001_1" geometry={nodes.CC_Base_Eye001_1.geometry} material={materials['Std_Cornea_R.001']} skeleton={nodes.CC_Base_Eye001_1.skeleton} morphTargetDictionary={nodes.CC_Base_Eye001_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Eye001_1.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Eye001_2" geometry={nodes.CC_Base_Eye001_2.geometry} material={materials['Std_Eye_L.001']} skeleton={nodes.CC_Base_Eye001_2.skeleton} morphTargetDictionary={nodes.CC_Base_Eye001_2.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Eye001_2.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Eye001_3" geometry={nodes.CC_Base_Eye001_3.geometry} material={materials['Std_Cornea_L.001']} skeleton={nodes.CC_Base_Eye001_3.skeleton} morphTargetDictionary={nodes.CC_Base_Eye001_3.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Eye001_3.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_EyeOcclusion001" geometry={nodes.CC_Base_EyeOcclusion001.geometry} material={materials['Std_Eye_Occlusion_R.001']} skeleton={nodes.CC_Base_EyeOcclusion001.skeleton} morphTargetDictionary={nodes.CC_Base_EyeOcclusion001.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_EyeOcclusion001.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_EyeOcclusion001_1" geometry={nodes.CC_Base_EyeOcclusion001_1.geometry} material={materials['Std_Eye_Occlusion_L.001']} skeleton={nodes.CC_Base_EyeOcclusion001_1.skeleton} morphTargetDictionary={nodes.CC_Base_EyeOcclusion001_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_EyeOcclusion001_1.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_TearLine001" geometry={nodes.CC_Base_TearLine001.geometry} material={materials['Std_Tearline_R.001']} skeleton={nodes.CC_Base_TearLine001.skeleton} morphTargetDictionary={nodes.CC_Base_TearLine001.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_TearLine001.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_TearLine001_1" geometry={nodes.CC_Base_TearLine001_1.geometry} material={materials['Std_Tearline_L.001']} skeleton={nodes.CC_Base_TearLine001_1.skeleton} morphTargetDictionary={nodes.CC_Base_TearLine001_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_TearLine001_1.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Teeth001" geometry={nodes.CC_Base_Teeth001.geometry} material={materials['Std_Upper_Teeth.001']} skeleton={nodes.CC_Base_Teeth001.skeleton} morphTargetDictionary={nodes.CC_Base_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Teeth001.morphTargetInfluences} />
        <skinnedMesh name="CC_Base_Teeth001_1" geometry={nodes.CC_Base_Teeth001_1.geometry} material={materials['Std_Lower_Teeth.001']} skeleton={nodes.CC_Base_Teeth001_1.skeleton} morphTargetDictionary={nodes.CC_Base_Teeth001_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Teeth001_1.morphTargetInfluences} />
      </group>
    </group>
  )
}

export default Smith;
